### ISSUE TITLE
菜单无法显示，进而无法切换BluetoothActivity和CameraUseActivity？

### ISSUE THREAD

**Issue by mindcont** [0x5e/RubiksCubeSolver#1]

**Comment by 0x5e** [comment]
额...很久以前的代码了,兼容性应该有问题吧,那时候是2.3.7= =ll

**Comment by mindcont** [comment]
( bingo !)
A:你造嘛，动力哥回复了我哎！棒棒哒！(*ﾟ▽ﾟ)ﾉ
B: ......

**Comment by 0x5e** [comment]
@mindcont 动力哥是??
前几天看到有个新闻是机器人一秒解魔方的..又有点想做了不过没时间😬
https://github.com/muodov/kociemba

**Comment by mindcont** [comment]
@0x5e 
[做做AI,造造人-动力老男孩](http://www.diy-robots.com/)不是你吗？

**Comment by 0x5e** [comment]
@mindcont 并不是。。。我也是跟着他学的，哈哈哈
